using System.Collections.Generic;
using Boomkop3;

namespace not_a_keylogger
{
    public class UserKeyInfo
    {
        private static Dictionary<UserKeys, string> _chars;
        public static Dictionary<UserKeys, string> chars
        {
            get
            {
                if (_chars == null) _chars = initDict();
                return _chars;
            }
        }
        public enum KeyState
        {
            RELEASED, PRESSED
        }
        private static Dictionary<UserKeys, string> initDict()
        {
            Dictionary<UserKeys, string> chars = new Dictionary<UserKeys, string>();
            (UserKeys key, string view)[] items = {
                (UserKeys.LEFT_MOUSE_BUTTON, ""),
                (UserKeys.RIGHT_MOUSE_BUTTON, ""),
                (UserKeys.MIDDLE_MOUSE_BUTTON, ""),
                (UserKeys.X1_MOUSE_BUTTON, ""),
                (UserKeys.X2_MOUSE_BUTTON, ""),
                (UserKeys.BACKSPACE, "\b \b"),
                (UserKeys.TAB, "\t"),
                (UserKeys.CLEAR, ""),
                (UserKeys.ENTER, "\r\n"),
                (UserKeys.SHIFT, ""),
                (UserKeys.CTRL, ""),
                (UserKeys.ALT, ""),
                (UserKeys.PAUSE, ""),
                (UserKeys.CAPS_LOCK, ""),
                (UserKeys.ESC, ""),
                (UserKeys.SPACEBAR, " "),
                (UserKeys.PAGE_UP, ""),
                (UserKeys.PAGE_DOWN, ""),
                (UserKeys.END, ""),
                (UserKeys.HOME, ""),
                (UserKeys.LEFT_ARROW, ""),
                (UserKeys.UP_ARROW, ""),
                (UserKeys.RIGHT_ARROW, ""),
                (UserKeys.DOWN_ARROW, ""),
                (UserKeys.SELECT, ""),
                (UserKeys.PRINT, ""),
                (UserKeys.EXECUTE, ""),
                (UserKeys.PRINT_SCREEN, ""),
                (UserKeys.INS, ""),
                (UserKeys.DEL, ""),
                (UserKeys.HELP, ""),
                (UserKeys._0, "0"),
                (UserKeys._1, "1"),
                (UserKeys._2, "2"),
                (UserKeys._3, "3"),
                (UserKeys._4, "4"),
                (UserKeys._5, "5"),
                (UserKeys._6, "6"),
                (UserKeys._7, "7"),
                (UserKeys._8, "8"),
                (UserKeys._9, "9"),
                (UserKeys.A, "A"),
                (UserKeys.B, "B"),
                (UserKeys.C, "C"),
                (UserKeys.D, "D"),
                (UserKeys.E, "E"),
                (UserKeys.F, "F"),
                (UserKeys.G, "G"),
                (UserKeys.H, "H"),
                (UserKeys.I, "I"),
                (UserKeys.J, "J"),
                (UserKeys.K, "K"),
                (UserKeys.L, "L"),
                (UserKeys.M, "M"),
                (UserKeys.N, "N"),
                (UserKeys.O, "O"),
                (UserKeys.P, "P"),
                (UserKeys.Q, "Q"),
                (UserKeys.R, "R"),
                (UserKeys.S, "S"),
                (UserKeys.T, "T"),
                (UserKeys.U, "U"),
                (UserKeys.V, "V"),
                (UserKeys.W, "W"),
                (UserKeys.X, "X"),
                (UserKeys.Y, "Y"),
                (UserKeys.Z, "Z"),
                (UserKeys.COMPUTER_SLEEP, ""),
                (UserKeys.NUMERICPAD_0, "0"),
                (UserKeys.NUMERICPAD_1, "1"),
                (UserKeys.NUMERICPAD_2, "2"),
                (UserKeys.NUMERICPAD_3, "3"),
                (UserKeys.NUMERICPAD_4, "4"),
                (UserKeys.NUMERICPAD_5, "5"),
                (UserKeys.NUMERICPAD_6, "6"),
                (UserKeys.NUMERICPAD_7, "7"),
                (UserKeys.NUMERICPAD_8, "8"),
                (UserKeys.NUMERICPAD_9, "9"),
                (UserKeys.MULTIPLY, "*"),
                (UserKeys.ADD, "+"),
                (UserKeys.SEPARATOR, ""),
                (UserKeys.SUBTRACT, "-"),
                (UserKeys.DECIMAL, "."),
                (UserKeys.DIVIDE, "/"),
                (UserKeys.F1, ""),
                (UserKeys.F2, ""),
                (UserKeys.F3, ""),
                (UserKeys.F4, ""),
                (UserKeys.F5, ""),
                (UserKeys.F6, ""),
                (UserKeys.F7, ""),
                (UserKeys.F8, ""),
                (UserKeys.F9, ""),
                (UserKeys.F10, ""),
                (UserKeys.F11, ""),
                (UserKeys.F12, ""),
                (UserKeys.F13, ""),
                (UserKeys.F14, ""),
                (UserKeys.F15, ""),
                (UserKeys.F16, ""),
                (UserKeys.F17, ""),
                (UserKeys.F18, ""),
                (UserKeys.F19, ""),
                (UserKeys.F20, ""),
                (UserKeys.F21, ""),
                (UserKeys.F22, ""),
                (UserKeys.F23, ""),
                (UserKeys.F24, ""),
                (UserKeys.NUM_LOCK, ""),
                (UserKeys.SCROLL_LOCK, ""),
                (UserKeys.LEFT_SHIFT, ""),
                (UserKeys.RIGHT_SHIFT, ""),
                (UserKeys.LEFT_CONTROL, ""),
                (UserKeys.RIGHT_CONTROL, ""),
                (UserKeys.LEFT_MENU, ""),
                (UserKeys.RIGHT_MENU, ""),
                (UserKeys.BROWSER_BACK, ""),
                (UserKeys.BROWSER_FORWARD, ""),
                (UserKeys.BROWSER_REFRESH, ""),
                (UserKeys.BROWSER_STOP, ""),
                (UserKeys.BROWSER_SEARCH, ""),
                (UserKeys.BROWSER_FAVORITES, ""),
                (UserKeys.VOLUME_MUTE, ""),
                (UserKeys.VOLUME_DOWN, ""),
                (UserKeys.VOLUME_UP, ""),
                (UserKeys.NEXT_TRACK, ""),
                (UserKeys.PREVIOUS_TRACK, ""),
                (UserKeys.STOP_MEDIA, ""),
                (UserKeys.PLAYPAUSE_MEDIA, ""),
                (UserKeys.START_MAIL, ""),
                (UserKeys.SELECT_MEDIA, ""),
                (UserKeys.PLAY, "")
            };
            items.ForEach(item => chars.Add(item.key, item.view));
            return chars;
        }
        public enum UserKeys
        {
            LEFT_MOUSE_BUTTON = 0X01,
            RIGHT_MOUSE_BUTTON = 0X02,
            MIDDLE_MOUSE_BUTTON = 0X04,
            X1_MOUSE_BUTTON = 0X05,
            X2_MOUSE_BUTTON = 0X06,
            BACKSPACE = 0X08,
            TAB = 0X09,
            CLEAR = 0X0C,
            ENTER = 0X0D,
            SHIFT = 0X10,
            CTRL = 0X11,
            ALT = 0X12,
            PAUSE = 0X13,
            CAPS_LOCK = 0X14,
            ESC = 0X1B,
            SPACEBAR = 0X20,
            PAGE_UP = 0X21,
            PAGE_DOWN = 0X22,
            END = 0X23,
            HOME = 0X24,
            LEFT_ARROW = 0X25,
            UP_ARROW = 0X26,
            RIGHT_ARROW = 0X27,
            DOWN_ARROW = 0X28,
            SELECT = 0X29,
            PRINT = 0X2A,
            EXECUTE = 0X2B,
            PRINT_SCREEN = 0X2C,
            INS = 0X2D,
            DEL = 0X2E,
            HELP = 0X2F,
            _0 = 0X30,
            _1 = 0X31,
            _2 = 0X32,
            _3 = 0X33,
            _4 = 0X34,
            _5 = 0X35,
            _6 = 0X36,
            _7 = 0X37,
            _8 = 0X38,
            _9 = 0X39,
            A = 0X41,
            B = 0X42,
            C = 0X43,
            D = 0X44,
            E = 0X45,
            F = 0X46,
            G = 0X47,
            H = 0X48,
            I = 0X49,
            J = 0X4A,
            K = 0X4B,
            L = 0X4C,
            M = 0X4D,
            N = 0X4E,
            O = 0X4F,
            P = 0X50,
            Q = 0X51,
            R = 0X52,
            S = 0X53,
            T = 0X54,
            U = 0X55,
            V = 0X56,
            W = 0X57,
            X = 0X58,
            Y = 0X59,
            Z = 0X5A,
            COMPUTER_SLEEP = 0X5F,
            NUMERICPAD_0 = 0X60,
            NUMERICPAD_1 = 0X61,
            NUMERICPAD_2 = 0X62,
            NUMERICPAD_3 = 0X63,
            NUMERICPAD_4 = 0X64,
            NUMERICPAD_5 = 0X65,
            NUMERICPAD_6 = 0X66,
            NUMERICPAD_7 = 0X67,
            NUMERICPAD_8 = 0X68,
            NUMERICPAD_9 = 0X69,
            MULTIPLY = 0X6A,
            ADD = 0X6B,
            SEPARATOR = 0X6C,
            SUBTRACT = 0X6D,
            DECIMAL = 0X6E,
            DIVIDE = 0X6F,
            F1 = 0X70,
            F2 = 0X71,
            F3 = 0X72,
            F4 = 0X73,
            F5 = 0X74,
            F6 = 0X75,
            F7 = 0X76,
            F8 = 0X77,
            F9 = 0X78,
            F10 = 0X79,
            F11 = 0X7A,
            F12 = 0X7B,
            F13 = 0X7C,
            F14 = 0X7D,
            F15 = 0X7E,
            F16 = 0X7F,
            F17 = 0X80,
            F18 = 0X81,
            F19 = 0X82,
            F20 = 0X83,
            F21 = 0X84,
            F22 = 0X85,
            F23 = 0X86,
            F24 = 0X87,
            NUM_LOCK = 0X90,
            SCROLL_LOCK = 0X91,
            LEFT_SHIFT = 0XA0,
            RIGHT_SHIFT = 0XA1,
            LEFT_CONTROL = 0XA2,
            RIGHT_CONTROL = 0XA3,
            LEFT_MENU = 0XA4,
            RIGHT_MENU = 0XA5,
            BROWSER_BACK = 0XA6,
            BROWSER_FORWARD = 0XA7,
            BROWSER_REFRESH = 0XA8,
            BROWSER_STOP = 0XA9,
            BROWSER_SEARCH = 0XAA,
            BROWSER_FAVORITES = 0XAB,
            VOLUME_MUTE = 0XAD,
            VOLUME_DOWN = 0XAE,
            VOLUME_UP = 0XAF,
            NEXT_TRACK = 0XB0,
            PREVIOUS_TRACK = 0XB1,
            STOP_MEDIA = 0XB2,
            PLAYPAUSE_MEDIA = 0XB3,
            START_MAIL = 0XB4,
            SELECT_MEDIA = 0XB5,
            PLAY = 0XFA
        }
    }
}
